### ISSUE TITLE
Only one of my friends appears on this

### ISSUE THREAD

**Issue by callmemainey** [sololegends/runelite-friend-finder#1]
All of my friends all have me added as well of course, but only one shows up.

**Comment by sololegends** [comment]
Thanks for the issue report!  

Can you give me your osrs username so I can check the server logs. I'll be able to check for bad data format and other things that may be causing issues. 

Thanks!

**Comment by callmemainey** [comment]
Absolutely!

It’s imMainey

Love this plugin by the way but yeah only works on my one friend
‘xfurthest’!

Thanks

**Comment by callmemainey** [comment]
Oh so this only works of both parties have the plugin installed?

**Comment by sololegends** [comment]
Yep! The way it works is those who have the plugin send their username, location, and the friend they have to the location server which will then deliver their location to those on their friends list so their client can display that location. 

Because I don't have access to Jagex's data on location (I wish lol) I have to gather and deliver the locations for the plugin myself.

**Comment by sololegends** [comment]
> Yep! The way it works is those who have the plugin send their username, location, and the friend they have to the location server which will then deliver their location to those on their friends list so their client can display that location.
> 
> Because I don't have access to Jagex's data on location (I wish lol) I have to gather and deliver the locations for the plugin myself.

NOTE: ONLY those on your friends list can pull down your player location, and nothing is stored on the server permanently.

**Comment by callmemainey** [comment]
Oh I see!!!!!

Man, that makes so much sense.

Great plugin Benjamin and thank you for your help! :)

**Comment by sololegends** [comment]
My pleasure! I'm glad you're enjoying it ^.^ 

If ever you have any features you'd like to see, I'm in the middle of the next update development now so this is the time!

**Comment by callmemainey** [comment]
I am. It really helped out a lot.

Umm, one thing that comes to mind, if you were to click on the friends name
on the side bar menu then an arrow that points in the direction the friend
is comes up on the minimap / the screen.

The fact Jagex doesn’t allow you to click on the the full map anymore (I’m
sure they did back in the day) is very frustrating when trying to meet up
with your friends. So having arrows without having to use the big map would
be great!

What do you think?

**Comment by sololegends** [comment]
That is on my list of things to do in fact! Should make it a LOT easier to meet up with friends!

**Comment by callmemainey** [comment]
Ahhh amazing!

When will we be blessed with this update?

I’ll have a more conscious think of whatever I could suggest also now that
you have offered :)

**Comment by sololegends** [comment]
I'm not sure when, I work on it when I have free time or are more AFK training ;) 

I'm hoping within the next couple weeks or so

**Comment by callmemainey** [comment]
ok sounds good! any other plugins you have made that i should be aware of?

**Comment by sololegends** [comment]
Nope, not yet, this is my first go at a plugin for Runelite :)

**Comment by callmemainey** [comment]
Oh ok! Wel great job so far as i mentioned! 

Question, any idea why this happens? 
![Screenshot 2023-08-22 at 23 48 41](https://github.com/sololegends/runelite-friend-finder/assets/139658642/0cc27a62-e5e5-4bb0-adc9-f8d0712b1a5b)

3 instances of my friend.

**Comment by sololegends** [comment]
Yep, that has already been fixed in the newest upcoming version.
