### ISSUE TITLE
The plugin stopped working for my main, but my alt still works

### ISSUE THREAD

**Issue by TheBrutalSkull** [sololegends/runelite-friend-finder#4]
My main is Brutaliaa and my alt is Halbertth. I can see fake friends on Halbertth but not on Brutaliaa. Can you please help me ?

It somehow just stopped working, it was before without issues.

**Comment by sololegends** [comment]
Are you talking about the debugging feature of drawing random generated "friends" on the map? 

Do you by chance have "Private" Chat set to "off"? That would cause no friends to be rendered at all regardless if they are real, or the debugging generation ones.

**Comment by TheBrutalSkull** [comment]
Oh well, it somehow fixed by itself so all good !
